### ISSUE TITLE
Feedback from AutoCore team

### ISSUE THREAD

**Issue by moelang** [eclipse-zenoh/zenoh-flow#36]
Hello zenoh-flow team,

We use zenoh-flow in our project, this framework is great and meets our expectations!

In the process of project development, we have met some scenarios and can't find a suitable solution.

Feedback is here and we look forward to discussing suitable solutions with you.

1. In graph node configuration, the current state is that a key can only have one value:
```yaml
configuration:
  key1: value1
  key2: value2
  key3: value3
```
But we need more fields to describe a key:
```yaml
configuration:
  - id: key1
    foo: value
    bar: value
    baz: value
  - id: key2
    foo: value
    bar: value
    baz: value
```
or:
```yaml
configuration:
  key1: 
    foo: value
    bar: value
    baz: value
  key2:
    foo: value
    bar: value
    baz: value
```
2. Development path of dynamic library are different with deployment path, we expect to change the default global graph args when runtime starting:

```yaml
args:
  release_path: /opt/release/bin
  default_input_id: Input
  default_output_id: Output
  default_config_foo: foo
operators:
  - id : MyOperator
    uri: file://{{release_path}}/libmy_operator.so
    inputs:
      - id: {{default_input_id}}
        type: i32
    outputs:
      - id: {{default_output_id}}
        type: i32
    configuration:
      config_foo: {{default_config_foo}}
```
and launch with development path:
```yaml
$ runtime --graph-file demo.yaml --runtime foo --release_path './build/bin'
```
More feedback will be updated after the demo test, looking forward to your reply：）
