### ISSUE TITLE
Global configuation parameters

### ISSUE THREAD

**Issue by gabrik** [eclipse-zenoh/zenoh-flow#90]
It would be interesting to have the possibility to define global configuration parameters.
E.g.

```yaml
flow: HelloWorld
configuration:
    my_global_parameter: my_global_value
operators:
  - id : Op1
    uri: file:///....
    inputs:
      - id: Name
        type: str
    outputs:
      - id: Greetings
        type: str
sources:
  - id : S1
    uri: file:///.....
    output:
      id: Name
      type: str
sinks:
  - id : Sink1
    uri: file:///....
    input:
      id: Greetings
      type: str
....
```

This avoids copying the same configuration multiple times along the Flow descriptor, as well as sharing parameters between nodes of the graph.
